# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeBoilerplate

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  target 'ReactNativeBoilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeBoilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeBoilerplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeBoilerplate-tvOS

end
